In [152]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [153]:

tabela = {
    'diariamente': {'3rd': [],},
    'semanalmente': {'Static': []}

}

In [ ]:
df_o = pd.read_excel('data/adriel_qualitativas.xlsx')

df = df_o[:]

df.columns = df.columns.str.strip()
df.columns = df.columns.str.replace('\n', '', regex=True)

print(len(df))

print(df.columns.tolist())

95

In [155]:
df = df.rename(columns={
    'Quais das seguintes ferramentas específicas de segurança de software você utiliza atualmente ou já utilizou anteriormente?':
    'ferramentas_utilizadas'
})

df_ferramentas = df[['ferramentas_utilizadas']]
df_ferramentas.insert(0, "Respondente", range(1, len(df_ferramentas) + 1))
df_ferramentas.head()

   Respondente      ferramentas_utilizadas
0            1                     AppScan
1            2                         NaN
2            3  SonarQube, Checkmarx, Xray
3            4   Sonatype, Ansible, Puppet
4            5               Snyk, Fortify

In [156]:
categorias = {
    "3rd Party Vulnerability Scanning": [
        "Dependabot", "PHP Security Checker", "Snyk", "Clair", "Blackduck",
        "Retire.JS", "SRC:CLR", "Anchore", "Node Security Platform", "Trivy",
        "Sonatype", "Whitesource"
    ],
    "Static Application Security Testing": [  # SAST
        "CodeQL", "CheckStyle", "Coverity", "SonarQube", "Bandit", "PHPStan",
        "LGTM", "Brakeman", "ESLint Security", "Dart Analyzer", "DevSkim"
    ],
    "Dynamic Application Security Testing": [  # DAST
        "Qark", "Checkmarx", "CFN NAG"
    ],
    "Secure Configuration/Hardening": [
        "Chef", "Ansible", "Terraform", "Puppet", "Phan", "Seccomp",
        "CloudCustodian", "Turbot"
    ],
    "Compliance/Hardening Checks": [
        "Bane", "Ansible-Lint", "Blackbox", "Puppet-Lint", "InSpec",
        "Kube Audit", "Foodcritic", "Cookstyle", "conftest"
    ],
    "Secrets Management": [
        "Pinterest Knox", "GitLeaks", "CyberArk Conjur",
        "ThoughtWorks Talisman", "Berglas", "Docker Secrets", "Trufflehog"
    ]
}

In [157]:
cols_ferramentas = [
    col for col in df.columns
    if "categorias de ferramentas" in str(col).lower()
]

print(f"\n{len(cols_ferramentas)} colunas encontradas para a pergunta das ferramentas:")
for c in cols_ferramentas:
    print("-", c)

df_categorias = df[cols_ferramentas].copy()

# percorre as colunas e renomeia se contiver uma das chaves de 'categorias'
novos_nomes = {}

for col in df_categorias.columns:
    for chave in categorias.keys():
        if chave.lower() in col.lower():  # compara ignorando maiúsculas/minúsculas
            novos_nomes[col] = chave
            break  # evita sobrescrever caso mais de uma chave apareça

# aplica o renomeamento
df_categorias = df_categorias.rename(columns=novos_nomes)
df_categorias.head()

6 colunas encontradas para a pergunta das ferramentas:
- Para cada uma das seguintes categorias de ferramentas de segurança automatizadas, indique com que frequência você as utiliza.  Considere marcar “Não Aplicável” para as categorias de ferramentas das quais você não utiliza. [3rd Party Vulnerability Scanning Tools]
- Para cada uma das seguintes categorias de ferramentas de segurança automatizadas, indique com que frequência você as utiliza.  Considere marcar “Não Aplicável” para as categorias de ferramentas das quais você não utiliza. [Static Application Security Testing Tools]
- Para cada uma das seguintes categorias de ferramentas de segurança automatizadas, indique com que frequência você as utiliza.  Considere marcar “Não Aplicável” para as categorias de ferramentas das quais você não utiliza. [Dynamic Application Security Testing Tools]
- Para cada uma das seguintes categorias de ferramentas de segurança automatizadas, indique com que frequência você as utiliza.  Considere marcar “Não Aplicável” para as categorias de ferramentas das quais você não utiliza. [Secure Configuration/Hardening Tools]
- Para cada uma das seguintes categorias de ferramentas de segurança automatizadas, indique com que frequência você as utiliza.  Considere marcar “Não Aplicável” para as categorias de ferramentas das quais você não utiliza. [Compliance/Hardening Checks Tools]
- Para cada uma das seguintes categorias de ferramentas de segurança automatizadas, indique com que frequência você as utiliza.  Considere marcar “Não Aplicável” para as categorias de ferramentas das quais você não utiliza. [Secrets Management Tools]

,3rd Party Vulnerability Scanning,Static Application Security Testing,Dynamic Application Security Testing,Secure Configuration/Hardening,Compliance/Hardening Checks,Secrets Management
0,Não Aplicável,Mensalmente,Diariamente,Não Aplicável,Não Aplicável,Anualmente
1,NaN,NaN,NaN,NaN,NaN,NaN
2,Não Aplicável,Semanalmente,Não Aplicável,Semanalmente,Não Aplicável,Semanalmente
3,Diariamente,Diariamente,Não Aplicável,Não Aplicável,Não Aplicável,Diariamente
4,Diariamente,Não Aplicável,Diariamente,Não Aplicável,Não Aplicável,Diariamente

In [158]:
escala_likert = [
    "Diariamente",
    "Semanalmente",
    "Mensalmente",
    "Anualmente",
    "Não Aplicável",
]

In [159]:
df_categorias.insert(0, "Respondente", range(1, len(df_categorias) + 1))

In [160]:
df_categorias.head()

,Respondente,3rd Party Vulnerability Scanning,Static Application Security Testing,Dynamic Application Security Testing,Secure Configuration/Hardening,Compliance/Hardening Checks,Secrets Management
0,1,Não Aplicável,Mensalmente,Diariamente,Não Aplicável,Não Aplicável,Anualmente
1,2,NaN,NaN,NaN,NaN,NaN,NaN
2,3,Não Aplicável,Semanalmente,Não Aplicável,Semanalmente,Não Aplicável,Semanalmente
3,4,Diariamente,Diariamente,Não Aplicável,Não Aplicável,Não Aplicável,Diariamente
4,5,Diariamente,Não Aplicável,Diariamente,Não Aplicável,Não Aplicável,Diariamente

In [161]:
df_3rd = df_categorias[['Respondente','3rd Party Vulnerability Scanning']]
df_3rd

    Respondente 3rd Party Vulnerability Scanning
0             1                    Não Aplicável
1             2                              NaN
2             3                    Não Aplicável
3             4                      Diariamente
4             5                      Diariamente
..          ...                              ...
90           91                      Diariamente
91           92                     Semanalmente
92           93                      Mensalmente
93           94                     Semanalmente
94           95                     Semanalmente

[95 rows x 2 columns]

In [162]:
df_merged = df_3rd.merge(df_ferramentas, on='Respondente', how='inner')

df_merged

,Respondente,3rd Party Vulnerability Scanning,ferramentas_utilizadas
0,1,Não Aplicável,AppScan
1,2,NaN,NaN
2,3,Não Aplicável,"SonarQube, Checkmarx, Xray"
3,4,Diariamente,"Sonatype, Ansible, Puppet"
4,5,Diariamente,"Snyk, Fortify"
...,...,...,...
90,91,Diariamente,"Dependabot, Snyk, Trivy, Sonatype, CheckStyle,..."
91,92,Semanalmente,"ESLint Security, Terraform, Burp Suite"
92,93,Mensalmente,"Dependabot, Snyk, Trivy, CodeQL, SonarQube, Ch..."
93,94,Semanalmente,"Dependabot, Snyk, Trivy, SonarQube, Bandit, Te..."
94,95,Semanalmente,"SonarQube, Terraform, CyberArk Conjur, AppScan"

In [163]:
# Categoria desejada
categoria = "3rd Party Vulnerability Scanning"

# Lista de ferramentas dessa categoria
ferramentas_categoria = categorias[categoria]

# Função para filtrar as ferramentas em cada célula
def filtrar_ferramentas(texto):
    if pd.isna(texto):
        return None
    
    # separar por vírgula
    ferramentas = [t.strip() for t in texto.split(",")]
    
    # manter apenas as ferramentas presentes na categoria
    filtradas = [f for f in ferramentas if f in ferramentas_categoria]
    
    # se nenhuma ferramenta pertence à categoria, retorna None
    return ", ".join(filtradas) if filtradas else None

# Aplicar ao df_merge
df_merged[f"ferramentas_{categoria}"] = df_merged["ferramentas_utilizadas"].apply(filtrar_ferramentas)

# Filtrar apenas as linhas que têm pelo menos 1 ferramenta da categoria
df_filtrado = df_merged[df_merged[f"ferramentas_{categoria}"].notna()]


df_filtrado = df_filtrado[df_filtrado['3rd Party Vulnerability Scanning'] == 'Diariamente']
df_filtrado.head()

,Respondente,3rd Party Vulnerability Scanning,ferramentas_utilizadas,ferramentas_3rd Party Vulnerability Scanning
3,4,Diariamente,"Sonatype, Ansible, Puppet",Sonatype
4,5,Diariamente,"Snyk, Fortify",Snyk
18,19,Diariamente,"Snyk, Trivy, Sonatype, SonarQube, ESLint Secur...","Snyk, Trivy, Sonatype"
24,25,Diariamente,"Dependabot, Snyk, Trivy, SonarQube, Checkmarx,...","Dependabot, Snyk, Trivy"
28,29,Diariamente,"Snyk, Sonatype, SonarQube, Checkmarx, Ansible,...","Snyk, Sonatype"

In [164]:
# Nome da coluna criada anteriormente
col = "ferramentas_3rd Party Vulnerability Scanning"

# Remover linhas vazias (caso existam)
df_tools = df_filtrado[df_filtrado[col].notna()].copy()

# Separar as ferramentas em listas
df_tools["lista"] = df_tools[col].apply(lambda x: [t.strip() for t in x.split(",")])

# Explodir listas em linhas
df_explodido = df_tools.explode("lista")

# Calcular a frequência
frequencias_diariamente = df_explodido["lista"].value_counts()

print(frequencias_diariamente)

lista
Snyk                      18
Trivy                     15
Dependabot                15
Sonatype                   9
Whitesource                4
Retire.JS                  4
Node Security Platform     3
PHP Security Checker       3
Clair                      1
SRC:CLR                    1
Blackduck                  1
Name: count, dtype: int64

# Salvando Diariamente

In [165]:
# Dicionário final onde vamos salvar as frequências
resultados = {}

for categoria, lista_ferramentas in categorias.items():
    df_selecionado = df_categorias[['Respondente',categoria]]
    df_merged = df_selecionado.merge(df_ferramentas, on='Respondente', how='inner')
    print(f"\nProcessando categoria: {categoria}")

    # Nome padronizado para variável
    col_ferramentas = f"ferramentas_{categoria}"

    # 1) Criar coluna filtrando as ferramentas da categoria
    def filtrar_ferramentas(texto):
        if pd.isna(texto):
            return None
        ferramentas = [t.strip() for t in texto.split(",")]
        filtradas = [f for f in ferramentas if f in lista_ferramentas]
        return ", ".join(filtradas) if filtradas else None

    df_merged[col_ferramentas] = df_merged["ferramentas_utilizadas"].apply(filtrar_ferramentas)

    # 2) Filtrar apenas quem usa a categoria "Diariamente"
    df_filtrado = df_merged[
        (df_merged[categoria] == "Diariamente") &
        (df_merged[col_ferramentas].notna())
    ].copy()

    # 3) Explodir as ferramentas e contar
    df_filtrado["lista"] = df_filtrado[col_ferramentas].apply(lambda x: [t.strip() for t in x.split(",")])
    df_explodido = df_filtrado.explode("lista")
    frequencias = df_explodido["lista"].value_counts()

    # 4) Nome automático para o resultado
    nome_variavel = f"frequencias_diariamente_{categoria.replace(' ', '_').replace('/', '_').lower()}"

    # Armazenar no dicionário final
    resultados[nome_variavel] = frequencias

    print(f"-> Frequências salvas como: {nome_variavel}")

Processando categoria: 3rd Party Vulnerability Scanning
-> Frequências salvas como: frequencias_diariamente_3rd_party_vulnerability_scanning

Processando categoria: Static Application Security Testing
-> Frequências salvas como: frequencias_diariamente_static_application_security_testing

Processando categoria: Dynamic Application Security Testing
-> Frequências salvas como: frequencias_diariamente_dynamic_application_security_testing

Processando categoria: Secure Configuration/Hardening
-> Frequências salvas como: frequencias_diariamente_secure_configuration_hardening

Processando categoria: Compliance/Hardening Checks
-> Frequências salvas como: frequencias_diariamente_compliance_hardening_checks

Processando categoria: Secrets Management
-> Frequências salvas como: frequencias_diariamente_secrets_management

In [166]:
import os
import pandas as pd

# Criar pasta caso não exista
os.makedirs("diariamente", exist_ok=True)

for nome, serie in resultados.items():
    df_saida = serie.reset_index()
    df_saida.columns = ["ferramenta", "frequencia"]
    
    # caminho do arquivo dentro da pasta
    caminho = f"diariamente/{nome}.csv"
    
    df_saida.to_csv(caminho, index=False)
    print(f"✔ CSV salvo: {caminho}")

✔ CSV salvo: diariamente/frequencias_diariamente_3rd_party_vulnerability_scanning.csv
✔ CSV salvo: diariamente/frequencias_diariamente_static_application_security_testing.csv
✔ CSV salvo: diariamente/frequencias_diariamente_dynamic_application_security_testing.csv
✔ CSV salvo: diariamente/frequencias_diariamente_secure_configuration_hardening.csv
✔ CSV salvo: diariamente/frequencias_diariamente_compliance_hardening_checks.csv
✔ CSV salvo: diariamente/frequencias_diariamente_secrets_management.csv

# Salvando Semanalmente

In [167]:
# Dicionário final onde vamos salvar as frequências
resultados = {}

for categoria, lista_ferramentas in categorias.items():
    df_selecionado = df_categorias[['Respondente',categoria]]
    df_merged = df_selecionado.merge(df_ferramentas, on='Respondente', how='inner')
    print(f"\nProcessando categoria: {categoria}")

    # Nome padronizado para variável
    col_ferramentas = f"ferramentas_{categoria}"

    # 1) Criar coluna filtrando as ferramentas da categoria
    def filtrar_ferramentas(texto):
        if pd.isna(texto):
            return None
        ferramentas = [t.strip() for t in texto.split(",")]
        filtradas = [f for f in ferramentas if f in lista_ferramentas]
        return ", ".join(filtradas) if filtradas else None

    df_merged[col_ferramentas] = df_merged["ferramentas_utilizadas"].apply(filtrar_ferramentas)

    # 2) Filtrar apenas quem usa a categoria "Semanalmente"
    df_filtrado = df_merged[
        (df_merged[categoria] == "Semanalmente") &
        (df_merged[col_ferramentas].notna())
    ].copy()

    # 3) Explodir as ferramentas e contar
    df_filtrado["lista"] = df_filtrado[col_ferramentas].apply(lambda x: [t.strip() for t in x.split(",")])
    df_explodido = df_filtrado.explode("lista")
    frequencias = df_explodido["lista"].value_counts()

    # 4) Nome automático para o resultado
    nome_variavel = f"frequencias_Semanalmente_{categoria.replace(' ', '_').replace('/', '_').lower()}"

    # Armazenar no dicionário final
    resultados[nome_variavel] = frequencias

    print(f"-> Frequências salvas como: {nome_variavel}")

Processando categoria: 3rd Party Vulnerability Scanning
-> Frequências salvas como: frequencias_Semanalmente_3rd_party_vulnerability_scanning

Processando categoria: Static Application Security Testing
-> Frequências salvas como: frequencias_Semanalmente_static_application_security_testing

Processando categoria: Dynamic Application Security Testing
-> Frequências salvas como: frequencias_Semanalmente_dynamic_application_security_testing

Processando categoria: Secure Configuration/Hardening
-> Frequências salvas como: frequencias_Semanalmente_secure_configuration_hardening

Processando categoria: Compliance/Hardening Checks
-> Frequências salvas como: frequencias_Semanalmente_compliance_hardening_checks

Processando categoria: Secrets Management
-> Frequências salvas como: frequencias_Semanalmente_secrets_management

In [168]:
import os
import pandas as pd

# Criar pasta caso não exista
os.makedirs("semanalmente", exist_ok=True)

for nome, serie in resultados.items():
    df_saida = serie.reset_index()
    df_saida.columns = ["ferramenta", "frequencia"]
    
    # caminho do arquivo dentro da pasta
    caminho = f"semanalmente/{nome}.csv"
    
    df_saida.to_csv(caminho, index=False)
    print(f"✔ CSV salvo: {caminho}")

✔ CSV salvo: semanalmente/frequencias_Semanalmente_3rd_party_vulnerability_scanning.csv
✔ CSV salvo: semanalmente/frequencias_Semanalmente_static_application_security_testing.csv
✔ CSV salvo: semanalmente/frequencias_Semanalmente_dynamic_application_security_testing.csv
✔ CSV salvo: semanalmente/frequencias_Semanalmente_secure_configuration_hardening.csv
✔ CSV salvo: semanalmente/frequencias_Semanalmente_compliance_hardening_checks.csv
✔ CSV salvo: semanalmente/frequencias_Semanalmente_secrets_management.csv

# Salvando Mensalmente

In [169]:
# Dicionário final onde vamos salvar as frequências
resultados = {}

for categoria, lista_ferramentas in categorias.items():
    df_selecionado = df_categorias[['Respondente',categoria]]
    df_merged = df_selecionado.merge(df_ferramentas, on='Respondente', how='inner')
    print(f"\nProcessando categoria: {categoria}")

    # Nome padronizado para variável
    col_ferramentas = f"ferramentas_{categoria}"

    # 1) Criar coluna filtrando as ferramentas da categoria
    def filtrar_ferramentas(texto):
        if pd.isna(texto):
            return None
        ferramentas = [t.strip() for t in texto.split(",")]
        filtradas = [f for f in ferramentas if f in lista_ferramentas]
        return ", ".join(filtradas) if filtradas else None

    df_merged[col_ferramentas] = df_merged["ferramentas_utilizadas"].apply(filtrar_ferramentas)

    # 2) Filtrar apenas quem usa a categoria "Mensalmente"
    df_filtrado = df_merged[
        (df_merged[categoria] == "Mensalmente") &
        (df_merged[col_ferramentas].notna())
    ].copy()

    # 3) Explodir as ferramentas e contar
    df_filtrado["lista"] = df_filtrado[col_ferramentas].apply(lambda x: [t.strip() for t in x.split(",")])
    df_explodido = df_filtrado.explode("lista")
    frequencias = df_explodido["lista"].value_counts()

    # 4) Nome automático para o resultado
    nome_variavel = f"frequencias_Mensalmente_{categoria.replace(' ', '_').replace('/', '_').lower()}"

    # Armazenar no dicionário final
    resultados[nome_variavel] = frequencias

    print(f"-> Frequências salvas como: {nome_variavel}")

Processando categoria: 3rd Party Vulnerability Scanning
-> Frequências salvas como: frequencias_Mensalmente_3rd_party_vulnerability_scanning

Processando categoria: Static Application Security Testing
-> Frequências salvas como: frequencias_Mensalmente_static_application_security_testing

Processando categoria: Dynamic Application Security Testing
-> Frequências salvas como: frequencias_Mensalmente_dynamic_application_security_testing

Processando categoria: Secure Configuration/Hardening
-> Frequências salvas como: frequencias_Mensalmente_secure_configuration_hardening

Processando categoria: Compliance/Hardening Checks
-> Frequências salvas como: frequencias_Mensalmente_compliance_hardening_checks

Processando categoria: Secrets Management
-> Frequências salvas como: frequencias_Mensalmente_secrets_management

In [170]:
import os
import pandas as pd

# Criar pasta caso não exista
os.makedirs("mensalmente", exist_ok=True)

for nome, serie in resultados.items():
    df_saida = serie.reset_index()
    df_saida.columns = ["ferramenta", "frequencia"]
    
    # caminho do arquivo dentro da pasta
    caminho = f"mensalmente/{nome}.csv"
    
    df_saida.to_csv(caminho, index=False)
    print(f"✔ CSV salvo: {caminho}")

✔ CSV salvo: mensalmente/frequencias_Mensalmente_3rd_party_vulnerability_scanning.csv
✔ CSV salvo: mensalmente/frequencias_Mensalmente_static_application_security_testing.csv
✔ CSV salvo: mensalmente/frequencias_Mensalmente_dynamic_application_security_testing.csv
✔ CSV salvo: mensalmente/frequencias_Mensalmente_secure_configuration_hardening.csv
✔ CSV salvo: mensalmente/frequencias_Mensalmente_compliance_hardening_checks.csv
✔ CSV salvo: mensalmente/frequencias_Mensalmente_secrets_management.csv

# Salvando Anualmente

In [171]:
# Dicionário final onde vamos salvar as frequências
resultados = {}

for categoria, lista_ferramentas in categorias.items():
    df_selecionado = df_categorias[['Respondente',categoria]]
    df_merged = df_selecionado.merge(df_ferramentas, on='Respondente', how='inner')
    print(f"\nProcessando categoria: {categoria}")

    # Nome padronizado para variável
    col_ferramentas = f"ferramentas_{categoria}"

    # 1) Criar coluna filtrando as ferramentas da categoria
    def filtrar_ferramentas(texto):
        if pd.isna(texto):
            return None
        ferramentas = [t.strip() for t in texto.split(",")]
        filtradas = [f for f in ferramentas if f in lista_ferramentas]
        return ", ".join(filtradas) if filtradas else None

    df_merged[col_ferramentas] = df_merged["ferramentas_utilizadas"].apply(filtrar_ferramentas)

    # 2) Filtrar apenas quem usa a categoria "Anualmente"
    df_filtrado = df_merged[
        (df_merged[categoria] == "Anualmente") &
        (df_merged[col_ferramentas].notna())
    ].copy()

    # 3) Explodir as ferramentas e contar
    df_filtrado["lista"] = df_filtrado[col_ferramentas].apply(lambda x: [t.strip() for t in x.split(",")])
    df_explodido = df_filtrado.explode("lista")
    frequencias = df_explodido["lista"].value_counts()

    # 4) Nome automático para o resultado
    nome_variavel = f"frequencias_Anualmente_{categoria.replace(' ', '_').replace('/', '_').lower()}"

    # Armazenar no dicionário final
    resultados[nome_variavel] = frequencias

    print(f"-> Frequências salvas como: {nome_variavel}")

Processando categoria: 3rd Party Vulnerability Scanning
-> Frequências salvas como: frequencias_Anualmente_3rd_party_vulnerability_scanning

Processando categoria: Static Application Security Testing
-> Frequências salvas como: frequencias_Anualmente_static_application_security_testing

Processando categoria: Dynamic Application Security Testing
-> Frequências salvas como: frequencias_Anualmente_dynamic_application_security_testing

Processando categoria: Secure Configuration/Hardening
-> Frequências salvas como: frequencias_Anualmente_secure_configuration_hardening

Processando categoria: Compliance/Hardening Checks
-> Frequências salvas como: frequencias_Anualmente_compliance_hardening_checks

Processando categoria: Secrets Management
-> Frequências salvas como: frequencias_Anualmente_secrets_management

In [172]:
import os
import pandas as pd

# Criar pasta caso não exista
os.makedirs("anualmente", exist_ok=True)

for nome, serie in resultados.items():
    df_saida = serie.reset_index()
    df_saida.columns = ["ferramenta", "frequencia"]
    
    # caminho do arquivo dentro da pasta
    caminho = f"anualmente/{nome}.csv"
    
    df_saida.to_csv(caminho, index=False)
    print(f"✔ CSV salvo: {caminho}")

✔ CSV salvo: anualmente/frequencias_Anualmente_3rd_party_vulnerability_scanning.csv
✔ CSV salvo: anualmente/frequencias_Anualmente_static_application_security_testing.csv
✔ CSV salvo: anualmente/frequencias_Anualmente_dynamic_application_security_testing.csv
✔ CSV salvo: anualmente/frequencias_Anualmente_secure_configuration_hardening.csv
✔ CSV salvo: anualmente/frequencias_Anualmente_compliance_hardening_checks.csv
✔ CSV salvo: anualmente/frequencias_Anualmente_secrets_management.csv

# Salvando Não Aplicável

In [173]:
# Dicionário final onde vamos salvar as frequências
resultados = {}

for categoria, lista_ferramentas in categorias.items():
    df_selecionado = df_categorias[['Respondente',categoria]]
    df_merged = df_selecionado.merge(df_ferramentas, on='Respondente', how='inner')
    print(f"\nProcessando categoria: {categoria}")

    # Nome padronizado para variável
    col_ferramentas = f"ferramentas_{categoria}"

    # 1) Criar coluna filtrando as ferramentas da categoria
    def filtrar_ferramentas(texto):
        if pd.isna(texto):
            return None
        ferramentas = [t.strip() for t in texto.split(",")]
        filtradas = [f for f in ferramentas if f in lista_ferramentas]
        return ", ".join(filtradas) if filtradas else None

    df_merged[col_ferramentas] = df_merged["ferramentas_utilizadas"].apply(filtrar_ferramentas)

    # 2) Filtrar apenas quem usa a categoria "Não Aplicável"
    df_filtrado = df_merged[
        (df_merged[categoria] == "Não Aplicável") &
        (df_merged[col_ferramentas].notna())
    ].copy()

    # 3) Explodir as ferramentas e contar
    df_filtrado["lista"] = df_filtrado[col_ferramentas].apply(lambda x: [t.strip() for t in x.split(",")])
    df_explodido = df_filtrado.explode("lista")
    frequencias = df_explodido["lista"].value_counts()

    # 4) Nome automático para o resultado
    nome_variavel = f"frequencias_nao_aplicavel_{categoria.replace(' ', '_').replace('/', '_').lower()}"

    # Armazenar no dicionário final
    resultados[nome_variavel] = frequencias

    print(f"-> Frequências salvas como: {nome_variavel}")

Processando categoria: 3rd Party Vulnerability Scanning
-> Frequências salvas como: frequencias_nao_aplicavel_3rd_party_vulnerability_scanning

Processando categoria: Static Application Security Testing
-> Frequências salvas como: frequencias_nao_aplicavel_static_application_security_testing

Processando categoria: Dynamic Application Security Testing
-> Frequências salvas como: frequencias_nao_aplicavel_dynamic_application_security_testing

Processando categoria: Secure Configuration/Hardening
-> Frequências salvas como: frequencias_nao_aplicavel_secure_configuration_hardening

Processando categoria: Compliance/Hardening Checks
-> Frequências salvas como: frequencias_nao_aplicavel_compliance_hardening_checks

Processando categoria: Secrets Management
-> Frequências salvas como: frequencias_nao_aplicavel_secrets_management

In [174]:
import os
import pandas as pd

# Criar pasta caso não exista
os.makedirs("nao_aplicavel", exist_ok=True)

for nome, serie in resultados.items():
    df_saida = serie.reset_index()
    df_saida.columns = ["ferramenta", "frequencia"]
    
    # caminho do arquivo dentro da pasta
    caminho = f"nao_aplicavel/{nome}.csv"
    
    df_saida.to_csv(caminho, index=False)
    print(f"✔ CSV salvo: {caminho}")

✔ CSV salvo: nao_aplicavel/frequencias_nao_aplicavel_3rd_party_vulnerability_scanning.csv
✔ CSV salvo: nao_aplicavel/frequencias_nao_aplicavel_static_application_security_testing.csv
✔ CSV salvo: nao_aplicavel/frequencias_nao_aplicavel_dynamic_application_security_testing.csv
✔ CSV salvo: nao_aplicavel/frequencias_nao_aplicavel_secure_configuration_hardening.csv
✔ CSV salvo: nao_aplicavel/frequencias_nao_aplicavel_compliance_hardening_checks.csv
✔ CSV salvo: nao_aplicavel/frequencias_nao_aplicavel_secrets_management.csv

# Criar planilha geral

In [175]:
import os
import pandas as pd

# Pastas e colunas desejadas
pastas = {
    "diariamente": "diariamente",
    "semanalmente": "semanalmente",
    "mensalmente": "mensalmente",
    "anualmente": "anualmente",
    "não aplicável": "nao_aplicavel"
}

# Criar DataFrame final
categorias_excel = list(categorias.keys())
colunas_excel = list(pastas.keys())

df_excel = pd.DataFrame(index=categorias_excel, columns=colunas_excel)

# Função para transformar CSV em string "ferramenta: freq; ..."
def csv_para_string(caminho):
    if not os.path.exists(caminho):
        return ""
    df = pd.read_csv(caminho)
    if df.empty:
        return ""
    
    texto = "; ".join(f"{row['ferramenta']}: {row['frequencia']}" 
                      for _, row in df.iterrows())
    
    # colocar quebra de linha após cada ';'
    return texto.replace("; ", ";\n")


# Preencher a planilha
for coluna_nome, nome_pasta in pastas.items():
    pasta = nome_pasta  # ex: diariamente/
    for categoria in categorias_excel:
        nome_csv = f"frequencias_{nome_pasta}_{categoria.replace(' ', '_').replace('/', '_').lower()}.csv"
        caminho = os.path.join(pasta, nome_csv)
        conteudo = csv_para_string(caminho)
        df_excel.loc[categoria, coluna_nome] = conteudo

# Salvar Excel
df_excel.to_excel("frequencias_categoria_por_periodo.xlsx")

print("✔ Planilha criada: frequencias_categoria_por_periodo.xlsx")

✔ Planilha criada: frequencias_categoria_por_periodo.xlsx